name: Tests

on:
  push:
    branches: [master]

jobs:
  e2e_tests:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        if: github.ref != 'refs/heads/master'
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: yarn test:e2e:ci
        env:
          FORCE_COLOR: 2
          MB_DEMO_URL: "https://shop.mercedes-benz.com/en-au/shop/vehicle/srp/demo"
          MB_USED_URL: "https://shop.mercedes-benz.com/en-au/shop/vehicle/srp/used"
          MB_CAR_PAGE_URL: "https://shop.mercedes-benz.com/en-au/shop/vehicle/pdp/AU2300080929T"
          MB_USED_CAR_WITH_FILTER_URL: "https://shop.mercedes-benz.com/en-au/shop/vehicle/srp/used?sort=relevance-ucos&assortment=vehicle&color_text="
          MB_USED_CAR_WITH_FILTER_AND_SORT_URL: "https://shop.mercedes-benz.com/en-au/shop/vehicle/srp/used?sort=price-desc-ucos&assortment=vehicle&color_text=BRILLANTBLUE%20metallic"

      - name: Save screenshots and trace in case of failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: failure-screenshots-trace-e2e
          path: test-results
          retention-days: 5
